version: "1.0"
info:
  model: int-scaffold
packages:
- name: JC_HelloWorld_DemoProject
  gitServerName: JC_TEST
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitBranch: main
- name: OpenWeatherClient
  version: "1.0"
  gitServerName: JC_TEST
  gitUrl: https://github.com/rahuldemocenter
  gitUsername: johnpcarter
  gitBranch: main
- name: JcPublicTools
  version: "1.0"
  gitServerName: JC_TEST
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitTag: v2.0.0
- name: echows
  version: "1.0"
  gitServerName: JC_TEST
  gitUrl: https://github.com/MarcFriedhoff
  gitUsername: johnpcarter
  gitBranch: master
- name: OrderEntry
  gitServerName: JC_TEST
  gitUrl: https://github.com/tlundstr
  gitUsername: johnpcarter
  gitBranch: master
services:
- serviceName: project.jc_helloworld_demo.integrations:testSoapService
  packages:
  - name: JC_HelloWorld_DemoProject
    version: "1.0"
  - name: JcPublicTools
    version: "1.0"
  - name: echows
    version: "1.0"
  - name: OpenWeatherClient
    version: "1.0"
- serviceName: echows.echows_.connectors:EchoPortType_Echo
  packages:
  - name: echows
    version: "1.0"
- serviceName: pub.client:soapClient
  packages:
  - name: WmPublic
    version: 11.1.0.0.2000
